### ISSUE TITLE
Won't install in my project from NuGet

### ISSUE THREAD

**Issue by Lawrence-Brad** [civicsource/enums#3]
NuGet installation failed on my project with the following message:

> Could not install package 'Archon.Enums 1.2.1'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

Should it work with .NET 4.5?

**Comment by chadly** [comment]
It targets [netstandard 1.5](https://docs.microsoft.com/en-us/dotnet/standard/library) so the lowest .net framework it would work with is 4.6.1
